### ISSUE TITLE
Fun errors at line 107

### ISSUE THREAD

**Issue by tschallacka** [ikr/money-math-php#4]
I just spent 2 hours tracing back why my calculations went awry ;-)

at line 107 you have 

 if (gmp_cmp(gmp_init($this->cents, 10), 0) < 0) {
            $ret = gmp_neg($ret);
        }

This returns a resource id to the GMP object instead of the values expected...

I altered it into  

if (gmp_cmp(gmp_init($this->cents, 10), 0) < 0) {
            $ret = gmp_strval(gmp_neg($ret));
        }

And the problems were fixed.

Was it intentional to leave it the gmp object when a negative number is encountered?

**Comment by ikr** [comment]
That's weird. With the `gmp_intval` following, that should not matter. Can you provide a failing test case? That would help a lot.

**Comment by tschallacka** [comment]
I just realised that i'm an idiot... I had that commented out... can't remember why. Sorry to take up your time with my idiocy.

**Comment by ikr** [comment]
:D no problem!
